### ISSUE TITLE
Improve send/receive dialogs

### ISSUE THREAD

**Issue by andynoack** [jopohl/urh#148]
Add new features:
- [x] Implementation: Show/Hide GUI elements depending on device has method e.g. ``` if hasattr(self.device, set_if_gain): if_slider.show() ```
- [x] collapsable gain spinboxes for detailed gain config (see https://github.com/jopohl/urh/issues/136). Test useability of slider and spinbox (slider left of spinbox)
- [x] consider supported gains for device e.g. RTL-SDR: get_tuner_gains and write max. value behind gain, e.g. Gain: (max. 400) or behind textfield ("/400") depending on the space in the dialog (see https://github.com/jopohl/urh/issues/177)
- [x] direct sampling support for RTL-SDR
- [x] ppm support for RTL-SDR (https://github.com/jopohl/urh/issues/189)
- [x] make freq correction configurable (RTL-SDR)
- [x] consider https://github.com/jopohl/urh/issues/133#issuecomment-282227945 for USRPs
- [x] AirSpy accepts only two values for sample rate: 2.5MSPS and 10MSPS. (see https://github.com/jopohl/urh/issues/166)
- [x] consider available samples rates for devices
- [x] show remaining RAM in receive dialog
- [x] make the current 60% RAM buffer configurable in options
- [x] also write success messages e.g. "successfully set sample rate to ..." to log in textbox, not only errors

**Comment by dkozel** [comment]
A useful set of USRP configuration settings for a single channel would include:
- [ ] Subdevice Specification (subdev_spec)
- [ ] TX/RX antenna
- [ ] TX/RX bandwidth

The valid values for all these can be queried with the multi_usrp API.
http://files.ettus.com/manual/classuhd_1_1usrp_1_1multi__usrp.html
