### ISSUE TITLE
Improve automatic analysis features

### ISSUE THREAD

**Issue by andynoack** [jopohl/urh#48]
- [x] Find most probable encoding (based on errors) #72
- [x] Detect participants based on RSSI #73
- [x] Detect labels automatically (addresses, length, crc, preamble, sync/constants, values, ...) #77 
  - How does this harmonize with auto assigning labelsets?
- [x] Autodetect different message types (length?, type?, timestamp?)
  - Isn't this the same as auto detecting labelsets? yes.

Configuration of analysis plugin to enable/disable different features. Analysis works in different stages, i.e. without any information (from scratch) and with given information (already labeled, chosen encoding, ...).
